baseURL = "https://chrisalbon.com/"
languageCode = "en-us"
title = "Chris Albon"
theme = "berbera"

pygmentsCodeFences=true
pygmentsUseClasses=true
canonifyURLs=true
publishDir="docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
